basePath: /api
definitions:
  dto.ItemAddRequest:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    required:
    - product_id
    - quantity
    type: object
  dto.OrderAddRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/dto.ItemAddRequest'
        type: array
      payment_method:
        enum:
        - qris
        - bcava
        type: string
      user_id:
        maxLength: 36
        type: string
    required:
    - items
    - payment_method
    - user_id
    type: object
info:
  contact: {}
  description: This is the Order Service for managing orders and items.
  title: Order Service API
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Fetch all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Fetch all orders
      tags:
      - Orders
    post:
      consumes:
      - application/json
      description: Create a new order with items
      parameters:
      - description: Order Request
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/dto.OrderAddRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Create a new order
      tags:
      - Orders
  /orders/{id}:
    get:
      consumes:
      - application/json
      description: Get order by spesific order id and include items
      parameters:
      - description: order id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Get order by id
      tags:
      - Orders
  /orders/users/{id}:
    get:
      consumes:
      - application/json
      description: Get all order by spesific user id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: get all order by user id
      tags:
      - Orders
swagger: "2.0"
